#!/usr/bin/env node
/* ============================================================
   한끗 — 일일 트렌드 갱신
   data/trends.json(원본)을 읽어 ① hermes 재수집·재분석 ② generatedAt=오늘 스탬프
   ③ 브라우저용 data/trends.js 생성. .github/workflows/daily-refresh.yml 이 매일 실행.

   실행: node scripts/refresh.mjs
   ============================================================ */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = join(root, 'data', 'trends.json');
const jsPath   = join(root, 'data', 'trends.js');

function todayISO() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/* ───────────────────── hermes 플러그 포인트 ─────────────────────
   실제로는 매일 여기서:
     1) 공식 API(네이버 지역/검색, 유튜브 데이터 등) + 수동 시드로 후보 수집
        (지도/SNS HTML 스크래핑 금지 — ToS·저작권)
     2) 광고 의심도 / 후기 신뢰도 / 만족도 재계산 (PRD 9장 룰셋)
     3) 사람 검수 게이트 통과분만 반영
     4) 실제로 갱신된 항목만 analyzedAt = 오늘 으로 스탬프
   지금은 no-op: 기존 분석을 그대로 둔다(거짓 신선도 방지).
   사이트는 항상 analyzedAt 대비 '오늘'을 계산해 신선도를 라이브로 보여주므로,
   여기서 거짓으로 날짜를 올리지 않는 것이 곧 신뢰다.
   ────────────────────────────────────────────────────────────── */
async function collectAndAnalyze(existing) {
  // TODO(hermes): 실제 수집·재분석으로 교체. 갱신된 항목에만 analyzedAt 갱신.
  // 예) const t = existing.find(x=>x.id==='ube'); if (reanalyzed) t.analyzedAt = todayISO();
  return existing;
}

const data = JSON.parse(await readFile(jsonPath, 'utf8'));
data.trends = await collectAndAnalyze(data.trends);
data.generatedAt = todayISO();

await writeFile(jsonPath, JSON.stringify(data, null, 2) + '\n', 'utf8');

const banner = '/* AUTO-GENERATED by scripts/refresh.mjs — 편집 금지. 원본: data/trends.json */\n';
await writeFile(jsPath, banner + 'window.HANGEUT_DATA = ' + JSON.stringify(data, null, 2) + ';\n', 'utf8');

const stale = data.trends.filter((t) => {
  const a = new Date(t.analyzedAt + 'T00:00:00'); const b = new Date();
  a.setHours(0, 0, 0, 0); b.setHours(0, 0, 0, 0);
  return Math.round((b - a) / 86400000) >= 14;
});
console.log(`✓ refreshed: generatedAt=${data.generatedAt}, ${data.trends.length} trends` +
  (stale.length ? `, ${stale.length} stale(>=14d): ${stale.map((t) => t.id).join(', ')}` : ', none stale'));
